# Generated by Django 5.2.6 on 2025-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='thread_id',
            field=models.CharField(default='temp', help_text='OpenAI Thread ID', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
