# Generated by Django 5.2.6 on 2025-10-01 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('basic_stats', '기본 통계 분석'), ('security_threat', '보안 위협 분석'), ('anomaly', '이상 행위 분석'), ('correlation', '상관관계 분석'), ('predictive', '예측 분석')], max_length=50)),
                ('result_data', models.JSONField(help_text='분석 결과를 JSON 형태로 저장')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='logs.logfile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('log_file', 'analysis_type')},
            },
        ),
    ]
