# Generated by Django 5.2.6 on 2025-09-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='log_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_entries', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('log_type', models.CharField(max_length=50)),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('raw_log', models.TextField()),
                ('metadata', models.TextField()),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logfile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
